# Generated by Django 5.2.4 on 2025-08-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('ath', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255)),
                ('total_tokens', models.IntegerField(default=0)),
                ('whitelist', models.BooleanField(default=False)),
                ('blacklist', models.BooleanField(default=False)),
                ('ath', models.IntegerField(default=0)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('faunded', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.admindev')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('scam', models.BooleanField(default=False)),
                ('ath', models.IntegerField(default=0)),
                ('migrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userdev')),
            ],
        ),
    ]
