# Generated by Django 5.2.4 on 2025-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
