# Generated by Django 5.2.4 on 2025-08-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userdev_faunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindev',
            name='twitter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
