# Generated by Django 5.2.4 on 2025-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_admindev_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindev',
            name='twitter',
            field=models.CharField(default='', max_length=255,unique = False),
        ),
    ]
