# Generated by Django 5.2.4 on 2025-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_admindev_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindev',
            name='total_devs',
            field=models.IntegerField(default=0),
        ),
    ]
