# Generated by Django 5.2.4 on 2025-08-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_admindev_total_devs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindev',
            name='total_devs',
        ),
    ]
