# Generated by Django 5.2.4 on 2025-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_admindev_total_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindev',
            name='total_devs',
            field=models.IntegerField(default=0),
        ),
    ]
