# Generated by Django 5.2.4 on 2025-08-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_admindev_total_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdev',
            name='faunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userdev'),
        ),
    ]
