# Generated by Django 5.2.4 on 2025-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_userdev_faunded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindev',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
