# Generated by Django 5.2.4 on 2025-08-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_admindev_total_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_pubkey', models.CharField(max_length=255)),
                ('sol_amount', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('slippage_percent', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('priority_fee_sol', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('start', models.BooleanField(default=False)),
                ('one_token_enabled', models.BooleanField(default=False)),
                ('whitelist_enabled', models.BooleanField(default=False)),
                ('ath_from', models.IntegerField(default=0)),
                ('total_trans_from', models.IntegerField(default=0)),
                ('median', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blacklist', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('total_tokens', models.IntegerField(default=0)),
                ('ath', models.IntegerField(default=0)),
                ('total_trans', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='scam',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='ath',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='faunded',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='faunded_by',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='userdev',
            name='uri',
        ),
        migrations.AddField(
            model_name='token',
            name='total_trans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='twitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.twitter'),
        ),
    ]
